version: "1.0"
services:
  database:
    image: mariadb:latest
    container_name: todoapp-db.docker
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=todo
      - TZ=Europe/Berlin
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
    volumes:
      - ./layout.sql/:/docker-entrypoint-initdb.d/init.sql
  frontend:
    build: ./todo-vue/
    container_name: todoapp.docker
    ports:
      - "8080:80"
  api:
    container_name: todoapp-api.docker
    build: ./API/
    ports:
      - "80:80"
    volumes:
      - ./API:/var/www/html
networks:
  default:
    name: todoapp